In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,])
print(arr1)

[1 2 3]


In [4]:
type(arr1)

numpy.ndarray

In [6]:
arr1.ndim

1

In [7]:
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)

[[1 2 3 4]
 [1 2 3 4]]


In [8]:
arr2.ndim

2

In [9]:
arr1.shape

(3,)

In [10]:
arr2.shape

(2, 4)

In [11]:
arr2.size

8

In [12]:
arr1.size

3

In [13]:
mx_1s = np.array([[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]]


In [15]:
mx_1s = np.ones((3,3))
print(mx_1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
mx_1s = np.ones((3,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [17]:
mx_0s =np.zeros((3,4))
print(mx_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
mx_0s = np.zeros((3,4) , dtype=bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [20]:
mx_0s = np.zeros((3,4) , dtype=str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [33]:
em_val = ''
print(bool(em_val))

False


In [25]:
em_mx = np.empty((3,7))
print(em_mx)

[[9.72985434e-312 9.72950454e-312 0.00000000e+000 0.00000000e+000
  2.37663529e-312 5.30276956e+180 1.57076922e-076]
 [4.57488309e-071 4.66421010e-086 3.35809007e-143 6.01433264e+175
  6.93885958e+218 5.56218858e+180 3.94356143e+180]
 [1.34001372e-075 7.67381242e-042 1.20743553e+161 7.86668096e-067
  6.46947238e-144 1.50008929e+248 2.59305228e-306]]


# Numpy Functions

# arange()

In [36]:

#np.arange(start,end,steps)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
even_arr = np.arange(1,13,2)
print(even_arr)

[ 1  3  5  7  9 11]


# linspace() : range ma array banave

In [40]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape() : array ne reshape kare 

In [42]:
arr_2d = arr_1d.reshape(4,3)
print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [45]:
 ar = np.arange(1,13).reshape(2,6)
 print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel : 2d ne 1d ma kre

In [46]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten : 2d ne 1d ma kre 

In [47]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose() : row ne column ma transfer kare

In [48]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [49]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# Mathematical Operation using numpy

In [50]:
import numpy as np

In [51]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [53]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [54]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [55]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
#element to element multiple thay
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [59]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [60]:
#matrix to matrix multiplu thay

In [61]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [62]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [63]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr1.max()

9

In [68]:
# max value ni index show kare
arr1.argmax()

8

In [71]:
arr1.max(axis = 0) # 0 column new show kre

array([7, 8, 9])

In [72]:
arr1.max(axis = 1) # 1 raw ne show kre

array([3, 6, 9])

In [73]:
arr1.min()

1

In [74]:
np.sum(arr1)

45

In [77]:
np.sum(arr1, axis = 0) # badhi column na sum malse

array([12, 15, 18])

In [78]:
np.sum(arr1, axis = 1) #badhi raw na sum malse

array([ 6, 15, 24])

In [79]:
np.mean(arr1) # average malse

5.0

In [81]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [82]:
np.std(arr1) # standard division male

2.581988897471611

In [83]:
np.exp(arr1) #expotional malse

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [84]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [85]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

#  Numpy Array slicing (:

In [86]:
import numpy as np

In [88]:
 mx = np.arange(1,101).reshape(10,10)
 print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [92]:
mx[0,0] # apeli index no element malse

1

In [90]:
mx[0,0].ndim

0

In [91]:
mx[0] # single raw malse

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
mx[:,0] #single column malse

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [96]:
mx[:,0:1] 

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [97]:
mx[:,0:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53],
       [61, 62, 63],
       [71, 72, 73],
       [81, 82, 83],
       [91, 92, 93]])

In [99]:
mx[1:4,1:4] #particular raw and column show karse

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [101]:
mx[:,1:3] #all raw ane selected column show karse

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

# numpy array concatination ans split

In [102]:
import numpy as np

In [110]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [108]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [111]:
#concatinate karva mate
arr1 + arr2 #anathi sum  thse

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [113]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [114]:
np.concatenate((arr1,arr2), axis = 1) #raw wise concatinate karva mate

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [115]:
np.vstack((arr1,arr2)) #vstack=vertical stack(column wise)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [116]:
np.hstack((arr1,arr2)) #horizontal stack (raw wise)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])